# Generated by Django 5.2.2 on 2025-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_funcionario_bairro_funcionario_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('gerente', 'Gerente'), ('caixa', 'Caixa'), ('atendente', 'Atendente'), ('cozinheiro', 'Cozinheiro'), ('estoquista', 'Estoquista'), ('administrador', 'Administrador'), ('faxineiro', 'Faxineiro')], max_length=100),
        ),
    ]
