# Generated by Django 5.2.2 on 2025-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_funcionario_uf_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dt_admissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dt_nacimento',
            field=models.DateField(),
        ),
    ]
