# Generated by Django 5.2.2 on 2025-06-10 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_funcionario_dt_admissao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='dt_nacimento',
            new_name='dt_nascimento',
        ),
    ]
