# Generated by Django 5.2.2 on 2025-06-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_fornecedor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor'},
        ),
    ]
