# Generated by Django 5.2.2 on 2025-06-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_fornecedor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('data', models.DateField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='cardapios/')),
                ('produtos', models.ManyToManyField(related_name='cardapios', to='api.produto')),
            ],
        ),
    ]
