# Generated by Django 5.2.2 on 2025-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_cardapio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='produtos',
            field=models.ManyToManyField(to='api.produto'),
        ),
    ]
