# Generated by Django 5.2.2 on 2025-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_cardapio_categoria_alter_cardapio_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardapio',
            name='data',
            field=models.DateField(),
        ),
    ]
