# Generated by Django 5.2.3 on 2025-06-26 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrinho',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='api.carrinho'),
        ),
    ]
