# Generated by Django 5.2.3 on 2025-06-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_pedido_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoitem',
            name='valor_item',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
