# Generated by Django 5.2.3 on 2025-06-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_pedidoitem_valor_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='selecionado',
            field=models.BooleanField(default=False),
        ),
    ]
