# Generated by Django 5.2.3 on 2025-06-27 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_produto_selecionado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='selecionado',
        ),
    ]
